### ISSUE TITLE
request: 모임 API 보완

### ISSUE THREAD

**Issue by unhyif** [JOY-RIDE/JOYRIDE#137]
우선 순위 별로 정리했습니다.

1. 모임 참여 시 성별/생년 검사
2. 개최한 모임/참가한 모임 리스트
3. 모임 북마크/해제
4. 북마크한 모임 리스트

**Comment by tkddls23** [comment]
확인했습니다

**Comment by unhyif** [comment]
> 확인했습니다

1번 제일 마지막에 해주셔도 될 것 같습니다!
