### ISSUE TITLE
request: 필요한 백엔드 작업

### ISSUE THREAD

**Issue by unhyif** [JOY-RIDE/JOYRIDE#173]
## 설명

- 모임 DB 비우기
- 모임 나이 필터 고치기
- 코스명(`courseName`)에 해당하는 모임 리스트
- 코스/모임 검색 (키워드 기준은 노션 회의록 참고)
- 모임 댓글 생성/삭제 API (수정은 상황 봐서)

**Comment by tkddls23** [comment]
- 비우기 완료
- 나이 필터 고치기 완료
